-- 우유와 요거트가 담긴 장바구니
SELECT m.CART_ID FROM
    (SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME = "Milk") AS m INNER JOIN
    (SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME = "Yogurt") AS y
        ON m.CART_ID = y.CART_ID
